name: flutter_maplestory
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.1
  flame_tiled: ^1.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/images/maps/
    - assets/images/maps/backgrounds/
    - assets/images/players/boy/
    - assets/images/monsters/Orange Mushroom/
    - assets/images/HUD/
